services:
  - type: web
    name: ai-agent-platform-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: ai_agent_platform_db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: CORS_ORIGIN
        value: https://your-frontend-domain.com

databases:
  - name: ai_agent_platform_db
    plan: starter
    ipAllowList: []